name: golang
display_name: Go
versions:
  - "1.19"
  - "1.20"
  - "1.21"
  - "1.22"
default_version: "1.21"
package_managers:
  - "go mod"
default_package_manager: "go mod"
download_urls:
  "1.21": "https://go.dev/dl/go1.21.0.windows-amd64.zip"
install_commands:
  - "go get {package}"
run_commands:
  go: "go"
environment_setup:
  - "go mod init example"
