name: python
display_name: Python
versions:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
default_version: "3.11"
package_managers:
  - pip
  - poetry
  - pipenv
default_package_manager: pip
download_urls:
  "3.11": "https://www.python.org/ftp/python/3.11.0/python-3.11.0-embed-amd64.zip"
install_commands:
  - "pip install {package}"
run_commands:
  python: "python"
  pip: "pip"
  poetry: "poetry"
  pipenv: "pipenv"
environment_setup:
  - "python -m venv .venv"
